name: BlueMapSetMarkers
version: '${project.version}'
main: org.siberianhusy.bluemapsetmarkers.BlueMapSetMarkers
api-version: '1.19'
commands:
  BlueMapSetMarkers:
    aliases: sm
    description: BlueMapSerMarkers help
  BlueMapSerMarkersAdmin:
    aliases: asm
    description: BlueMapSetMarkers Admin help
    permission: bluemapsetmarkers.admin


